spring:
  application:
    name: Fruitables_shop
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fruitables_shop_db
    username: root
    password: Mesieutocutedechuong@1976
  jpa:
    hibernate:
      ddl-auto: none
  data:
    web:
      pageable:
        one-indexed-parameters: true
  servlet:
    multipart:
      max-file-size: 10MB

file_up_load:
  root-path: src/main/resources/static/images
  user-image-path: src/main/resources/static/images/userImage
  product-image-path: src/main/resources/static/images/productImage

jwt:
  base64-secret: MKCiJazbDkyYqgwUmao18FitLPYmvBJ95RJMKdXzN/TDs6FS1npEDwP/9j2lYLZCKZLuxonmK5fR5v59Ik8HzA==
  access-token-validity-in-seconds: 3600
  refresh-token-validity-in-seconds: 2592000



