spring:
  application:
    name: Fruitables_shop
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fruitables_shop_db
    username: root
    password: Vinhhung03#
  jpa:
    hibernate:
      ddl-auto: none
  data:
    web:
      pageable:
        one-indexed-parameters: true

jwt:
  base64-secret: MKCiJazbDkyYqgwUmao18FitLPYmvBJ95RJMKdXzN/TDs6FS1npEDwP/9j2lYLZCKZLuxonmK5fR5v59Ik8HzA==
  access-token-validity-in-seconds: 864000
  refresh-token-validity-in-seconds: 8640000



