spring:
  application:
    name: Fruitables_shop
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fruitables_shop_db
    username: root
    password: Vinhhung03#
  jpa:
    hibernate:
      ddl-auto: none

jwt:
  privateKey: SF8RvR6MqTE+Qf/OwgDL3t9I9DGvtHRt2sQhTxpAFfQ=
  expiration: 86400000  # 1 ngày

